### ISSUE TITLE
Not working on Huawei RIO-L02 with Android 5.1

### ISSUE THREAD

**Issue by postacik** [hemanthrajv/flutter_compass#39]
Hi, 
The library (v0.4.3) works fine on new devices but when I try to run it on a Huawei RIO-L02 with Android 5.1, it does not work.

`this.sensorManager.getDefaultSensor(sensorType)` function returns null with both of the following sensor types:

`Sensor.TYPE_ROTATION_VECTOR and Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR`

However the following compass implemention which uses Sensor.TYPE_ACCELEROMETER and Sensor.TYPE_MAGNETIC_FIELD sensors to calculate the azimuth work without any problems on the same device:

https://github.com/iutinvg/compass/blob/48347d7ab23f1bf1801791d561fb5ae452217046/app/src/main/java/com/sevencrayons/compass/Compass.java

Is it possible to add this alternative as a fallback method in the library?

**Comment by ebjerkelund** [comment]
+1 on this one. Doesn't work on my Samsung 5.1.1

**Comment by paulosousadias** [comment]
+1 also. Doesn't work on some phones because it lacks Sensor.TYPE_ROTATION_VECTOR and Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR. But it has the Sensor.TYPE_ACCELEROMETER and Sensor.TYPE_MAGNETIC_FIELD which works for example on https://pub.dev/packages/simple_flutter_compass (which is not maintained and why trying to use this one.
