### ISSUE TITLE
Show how accurate the compass is

### ISSUE THREAD

**Issue by dark-chocolate** [hemanthrajv/flutter_compass#8]
## Feature Request
It would be nice to see how accurate the compass is (using Sensor manager). 

### Workaround
In java when you implement `SensorEventListener`, you have option to override `onAccuracyChanged()` 

```
@Override
    public void onAccuracyChanged(Sensor sensor, int accuracy)
    {
        switch (accuracy)
        {
            case SensorManager.SENSOR_STATUS_ACCURACY_LOW:
                break;

            case SensorManager.SENSOR_STATUS_ACCURACY_MEDIUM:
                break;

            case SensorManager.SENSOR_STATUS_ACCURACY_HIGH:
                break;

            case SensorManager.SENSOR_STATUS_UNRELIABLE:
               break;
        }

    }
```

**Comment by ened** [comment]
@dark-chocolate is there a similar function on iOS?

**Comment by dark-chocolate** [comment]
AFAIK, there is no function like this in iOS.

**Comment by mrhabibi** [comment]
Any plan to implement this feature? I think it's one of the most vital thing for compass feature in Android to check and to calibrate the compass as well.

**Comment by futurnaingenieur** [comment]
If I'm not mistaken, we can use headingAccuracy of CLHeading for iOS. I did a small test and passed it. Seems to work. The value is actually the delta in degrees. From what I've experienced I can say that under 15 is already pretty good (tested on iPhone 7).

Regarding Android it's also pretty simple since the method onAccuracyChanged is already in the code. I just retrieved the value back to flutter code. Values are:

`/// The values returned by this sensor cannot be trusted, calibration is
  /// needed or the environment doesn't allow readings
  static const int SENSOR_STATUS_UNRELIABLE = 0;

  /// This sensor is reporting data with low accuracy, calibration with the
  /// environment is needed
  static const int SENSOR_STATUS_ACCURACY_LOW = 1;

  /// This sensor is reporting data with an average level of accuracy,
  /// calibration with the environment may improve the readings
  static const int SENSOR_STATUS_ACCURACY_MEDIUM = 2;

  /// This sensor is reporting data with maximum accuracy
  static const int SENSOR_STATUS_ACCURACY_HIGH = 3;
`

**Comment by postacik** [comment]
@futurnaingenieur , can you share your Android and iOS code for accuracy?

**Comment by ebjerkelund** [comment]
I can see the onAccuracyChanged listener in the java code. It as an empty method with no event back to Flutter. Any plans to fill this in?

**Comment by ebjerkelund** [comment]
> I can see the onAccuracyChanged listener in the java code. It as an empty method with no event back to Flutter. Any plans to fill this in?

Looking further -- I was looking at an old version.

But I see that the java code in this project has what looks like accuracy code returned. But the latest flutter package posted in pub.dev has yet to catch up with this version. Any plans to repackage the flutter component?

**Comment by hemanthrajv** [comment]
Latest versions have accuracy.
